"""updates

Revision ID: e366224ef7f3
Revises: 3f1163f10a77
Create Date: 2023-03-11 00:52:15.152982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e366224ef7f3'
down_revision = '3f1163f10a77'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('location', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'location')
    # ### end Alembic commands ###
